resolver: nightly-2021-07-23
packages:
- .
extra-deps:
- git: https://github.com/locallycompact/composite
  commit: 5644183439960e63d06ef8ec5e85c25356c6b1fc
  subdirs:
  - composite-base
  - composite-aeson
- composite-aeson-throw-0.1.0.0
allow-newer: true
nix:
  packages: [zlib]
  enable: false
